"""
Django settings for mtec_wifi project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import requests


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e_c*-w_$h%7t0#bub(ei53r%gyp03*lty67x24-i_n4^&%y1!t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # Add your domain or IP for testing

# Application definition
INSTALLED_APPS = [
    'core',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'django_daraja',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mtec_wifi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mtec_wifi.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'  # Set to EAT for Kenya
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Config
JAZZMIN_SETTINGS = {
    "site_title": "MTEC Admin",
    "site_header": "MTEC",
    "site_brand": "MTEC WiFi Admin",
    "site_logo": None,
    "welcome_sign": "Welcome to MTEC WiFi Admin",
    "copyright": "MTEC © 2025",
    "search_model": ["auth.User", "core.Plan"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "usermenu_links": [
        {"model": "auth.user"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "core"],
    "custom_css": "core/css/custom.css",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "core.Plan": "fas fa-box",
        "core.Voucher": "fas fa-ticket-alt",
        "core.Payment": "fas fa-money-bill-wave",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "theme": "darkly",
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "vertical_tabs"},
}

# M-Pesa Configuration (Daraja Sandbox)
MPESA_ENV = 'sandbox'  # Use 'live' for production
MPESA_CONSUMER_KEY = 'Y0d8VdG0QmcTMpy7NWelQHswBtAd'  # Your Daraja Consumer Key
MPESA_CONSUMER_SECRET = 'gytARKSXjayWFVbl1dObFGurbACmlM0b6jrUoxqK1uYZZMoviF8hdAnhE7v9h9Gt'  # Replace with your secret from Daraja
MPESA_SHORTCODE = 174379  # Your Business Shortcode
MPESA_PASSKEY = 'bfb279f9a9b9dbcfe158e97dd71a467cd2e0c893059b10f78e6b72ad1ed2c91'  # Your Passkey
MPESA_INITIATOR_NAME = 'testapi'  # Initiator name (set in Daraja)
MPESA_SECURITY_CREDENTIAL = 'm8h0Uu26Gaqfq2XLeHO9E3TAYl6okP9bEhNVqhgKmGKTGkP2'  # Generate via Daraja portal
MPESA_CALLBACK_URL = 'http://127.0.0.1:8000/mpesa/stk-push/callback/'  # Local for testing; use ngrok or public URL
MPESA_CONFIRMATION_URL = MPESA_CALLBACK_URL  # Same for now
MPESA_VALIDATION_URL = MPESA_CALLBACK_URL  # Same for now
MPESA_TIMEOUT_URL = MPESA_CALLBACK_URL  # Same for now